### ISSUE TITLE
could not decode image

### ISSUE THREAD

**Issue by muzammilrehman** [bpgoldsb/no-tab-left-behind#2]
while installing the extension on chrome (version:89.0.4389.90 (Official Build) (x86_64) )I am getting the following error. Tried multiple times same error. 

<img width="1668" alt="Screen Shot 2021-03-16 at 3 51 21 PM" src="https://user-images.githubusercontent.com/3695663/111293851-b6b8fa80-866f-11eb-9d32-7e96d6082286.png">

**Comment by bpgoldsb** [comment]
Is this when installing from the Chrome Store or v0.0.8 in the Github releases page?

**Comment by muzammilrehman** [comment]
Version: 0.0.6

**Comment by bpgoldsb** [comment]
This should be fixed in v0.0.8.  Feel free to try from the Github Releases page https://github.com/bpgoldsb/no-tab-left-behind/releases/tag/v0.0.8

Or I'll update this issue when v0.0.8 hits the store.

**Comment by muzammilrehman** [comment]
was able to install 0.0.8. thanks for the fix
